### ISSUE TITLE
Compilation / install process fails

### ISSUE THREAD

**Issue by OriginLabs-Iguernlala** [KiFoundation/ki-tools#1]
## Summary of Bugs

**1/2**

I followed the README.md to build and install binaries, but the process fails at `make install` with errors:
```
go: writing go.mod cache: mkdir /usr/local/go/pkg/mod: permission denied
go: writing go.mod cache: mkdir /usr/local/go/pkg/mod: permission denied
go: writing go.mod cache: mkdir /usr/local/go/pkg/mod: permission denied
...
```
I'm not quite familiar with Go, but I thought something went wrong in configuration variables. So I changed:
```
GOPATH=/usr/local/go
```
to
```
GOPATH=$HOME/go
```
without re-executing the rest of the shell commands (maybe I should ?):
```
PATH=$GOPATH/bin:$PATH
mkdir -p $HOME/go/bin
echo "export PATH=$PATH:$(go env GOPATH)/bin" >> ~/.bash_profile
source ~/.bash_profile
```
This modification allowed me to successfully run `make install` command

**2/2**
`kid version --long` failed because `kid` was not found. This is likely due to the fact that `$GOPATH` was not correct initially, and thus, `PATH=$GOPATH/bin:$PATH` does not actually add `$HOME/go/bin` to the PATH

After these fixes, I managed to configure and run a node. But not able to become a validator yet without faucet tokens

## Version

commit ID: 573b732a6247fe55ad2aafafa300fa698f7d3ab2

## Steps to Reproduce

Run the commands of README.md on a fresh install

**Comment by TarekAwwad** [comment]
Please report your Go version and OS.

**Comment by OriginLabs-Iguernlala** [comment]
Go version: the one given in the README of commit 573b732a6247fe55ad2aafafa300fa698f7d3ab2
OS version: Xubuntu 18.04

**Comment by TarekAwwad** [comment]
Thank you for reporting this issue 👍. I just updated the path setting commands (commit  https://github.com/KiFoundation/ki-tools/commit/59d3c8d79bce41d9aba85028c3056970dd967433). Please re-open this issue if the problem persist.
