### ISSUE TITLE
wallet address possible mismatch 

### ISSUE THREAD

**Issue by flug** [KiFoundation/ki-tools#3]
I followed that order: 

```
kicli keys add Flug --home ./kicli/

```
via the website: https://medium.com/ki-foundation/welcome-to-the-kazeki-testnet-840fa97ba29

and by adding my passphrase I realized that the address returned was not the same as the one of my wallet so it is impossible to start the validator with this command: 

```
kicli tx staking create-validator
                  --commission-max-change-rate=0.1 \
                  --commission-max-rate=0.1 \
                  --commission-rate=0.1 \
                  --min-self-delegation=1 \
                  --amount=1000000tki \
                  --pubkey `kid tendermint show-validator --home ./kid/` \
                  --moniker=<MY VALIDATOR> \
                  --chain-id=KiChain-t-1 \
                  --from=Flug \
                  -home. -kicli.
```

```
ERROR: {"codespace": "sdk", "code":9, "message": "account <TOKEN> does not exist"}
```
any ideas?

**Comment by TarekAwwad** [comment]
Hello @flug. 
How did you create your Wallet and what do you mean by "adding my passphrase".

In all cases, in your staking command you have a problem with the `--home` flag:
It should be `--home ./kicli` (assuming that you are in the kicli/ parent folder"

**Comment by flug** [comment]
yeah yeah yeah the home is indeed the one you mentioned (copy and paste problem I guess). 

For the passphrase that is requested via this command: ```kicli keys add Flug --home ./kicli/```

**Comment by TarekAwwad** [comment]
@flug ok then here are two things to keep in mind:
- The address on which you have tokens is not the one that will be used for the staking as it was created outside the ki-tools (through the web wallet in imagine). You can still import it but this is not essential. 
- When you add a key with `kicli keys add Flug --home ./kicli/` you are creating a new wallet (address and keys) and storing in the machine. This is a different one that what you created earlier. The passphrase you are asked to enter is a normal password (like the passwords you use for your accounts online) to  protect your keys.  You are not supposed to enter your mnemonic (24 words) there. A mnemonic will be generated for the new wallet when this command is launched and the password is entered.

So here is what you need to do :
- Add a new key (as explained in the second point above)
- Send tokens to the new address from the address where you already have tokens
- Create your validator with the  `kicli tx staking create-validator...` command

I Hope this helps

**Comment by TarekAwwad** [comment]
@flug hope this helped. I'll close this issue for now. Feel free to reopen it if the problem persists
